sudo: false
language: generic
matrix:
  include:
  - os: linux
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
  timeout: 3600
before_install:
- travis_wait 45 bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk -pdf -interaction=nonstopmode -halt-on-error abstract.tex
after_success: 
deploy:
  provider: releases
  api_key:
    secure: p3ylqLLVu4AcqPE8iiUGqHgsxXB53hmzUvnyLjEr/weMZqOoBDEqMwb1We6vZH59C5SrApwOrxd+1/RCSwFQKuUimIoV9UodJNVrTPrua4uMbzh+s6VEpxU4J8t2QtP4x2ALB0zpZScRUdqgUirgmIZfHEA9vZQs45z8HeQjoDSbATuWHxU8RLxmwZPcw8Bl4OjjrRuB8XP+cRyID6ItcKFoo8V3spNL+Y7lqNqgVQRVeI7YnVZQPsqf/P0cqLljDaMlJKjg2kUvutf/y8rH1TvOwrLrRz85W/MaNbPsH2rEBwhwbWToPmOziqIwDpO/yoQEJUo5Vh5nepslJTp715h1m+s+PXrrZ7L6VL/YX+6KTAJ8P9ETJbo2B7nebavyhe5jH+mSRGTHWehEXTh+oA43nS9LXj2LyiRaJp1MQBLV31B97yQaP4ciD1XDPht0xebQEONfuJck/ac0sKmlvC2PdWS4wPUqa+U2U9f5JiIR3nRue3/ZILlca/FbPmAq2/PhjBXsGAXp1BItF9qEWhHp11B5Keo0GSp7BGZy6GTU7p16k3JfOawM+CAEuTclG6EEr4w/9VTNKb9s2yIlPBxc1SSa6ZMaST88uVOtnC1LAUyrGqHgFLXBnZM6E1Dgs//0WIZEBhm9Mz39ifg7PLmY0vS+ak1SukwA7k3wtnc=
  file: abstract.pdf
  on:
    repo: skulumani/2018_sspi_abstract
    tags: true
